# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - openstack-cover-jobs
      - docs-on-readthedocs
      - openstack-python35-jobs
      - openstack-python36-jobs
    vars:
      rtd_webhook_id: '47578'
      rtd_project_name: 'airship-armada'
    check:
      jobs:
        - openstack-tox-pep8
        - armada-chart-build-gate
        - armada-chart-build-latest-htk
        - armada-docker-build-gate-ubuntu
        - armada-docker-build-gate-opensuse
        - armada-airskiff-deploy
    gate:
      jobs:
        - openstack-tox-pep8
        - armada-chart-build-gate
        - armada-docker-build-gate-ubuntu
        - armada-docker-build-gate-opensuse
    post:
      jobs:
        - armada-docker-publish-ubuntu
        - armada-docker-publish-opensuse
        - armada-upload-git-mirror

- nodeset:
    name: armada-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: armada-chart-build-gate
    description: |
      Builds Armada and Tiller charts using pinned Helm toolkit.
    timeout: 900
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: armada-single-node

- job:
    name: armada-chart-build-latest-htk
    description: |
      Builds Armada and Tiller charts using latest Helm toolkit.
    timeout: 900
    voting: false
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: armada-single-node
    vars:
      HTK_COMMIT: master

- job:
    name: armada-docker-build-gate-ubuntu
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    vars:
      publish: false
      distro: ubuntu_bionic
      tags:
        dynamic:
          patch_set: true

- job:
    name: armada-docker-build-gate-opensuse
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    vars:
      publish: false
      distro: opensuse_15
      tags:
        dynamic:
          patch_set: true

- job:
    name: armada-airskiff-deploy
    nodeset: armada-single-node
    description: |
      Deploy Memcached using Airskiff and submitted Armada changes.
    timeout: 9600
    voting: false
    pre-run:
      - tools/gate/playbooks/airskiff-reduce-site.yaml
      - tools/gate/playbooks/git-config.yaml
    run: tools/gate/playbooks/airskiff-deploy.yaml
    post-run: tools/gate/playbooks/debug-report.yaml
    required-projects:
      - airship/deckhand
      - airship/pegleg
      - airship/shipyard
      - airship/treasuremap
      - openstack/openstack-helm-infra
    vars:
      OSH_INFRA_PATH: "../../openstack/openstack-helm-infra"
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^examples/.*$
      - ^releasenotes/.*$
      - ^swagger/.*$

- job:
    name: armada-docker-publish-ubuntu
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    secrets:
      - airship_armada_quay_creds
    vars:
      publish: true
      distro: ubuntu_bionic
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- job:
    name: armada-docker-publish-opensuse
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    secrets:
      - airship_armada_quay_creds
    vars:
      publish: true
      distro: opensuse_15
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- secret:
    name: airship_armada_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - mQ5xMKaU6+ug5Zp+LK5hfwbFamnW9hK2QVQOA7ylcoTMh8yz66YcgDjGJjbT2c66NF8eg
          f279ODNmGe5pYepdR8/fU/aQ2pTVVvrF1bt0fcon8xxEZGuWnCftYZjO6Ogq+HWWwwnW0
          HLcvnFK3GhGBJkYCG9742PxuLpDOYDSiK3jRCN1tgdY+vcHpm7bwqyhzywj7ar4lsk8Gk
          d9Z57xkcURuw/GEBf8tHzd2PTAj3Oao6hKMTdCVhYZejjNNR34GPhGIvipb7m/dNIzT2c
          j4a/Kq3HcqVog1OiCkSn4jRlIcD1Jgl/cyJyEz6dZCP2W16X/qwzDD8YUSsTPt4Jc6s/U
          hD/aye5f1Jwoiyy23BM7BJ8s8eoioYsubV3TUGNQv64UxRnd4nPyWW2QssfAlA2fsww2v
          D9nLjmYuj4t8IzfQVd4ZLwBUKrb1q1au8bR3jYd8x2RaYjAVr4aPXQLzeXR7k0kZ9QgYO
          PetkCkf2vly8UYtonaM0odf7X1KfKgCOU+urXWMnDVU3SEaMH5f51NnW8Xb5NmCk/S9vz
          MVl6IR/ZCa9q7sIH40B2Tt61AsU1RjIyAahU6fkg/pW19uBv7zI6BDSZUiEh662MnK4z1
          O5n0771VjSa2aqpP1+iTkDWqobcSvgvHWQCM4Cv4fBO//E7s/LV0FIayQYbm2k=
      password: !encrypted/pkcs1-oaep
        - nATf8olUzHg6pBmRJ2KF9NI48axKYtuFn7j8R8iKRfV3R7NW3eq89gsk5m9DVq4+GUEGw
          ZxLRjy2/F31Xnw2snGf7Pj+33O1NRSZ7D/UqKSu07tS0qkRn4rWK6U4tO1crHb7NPqd3I
          rziVgOCTBpaKNLBlEEYqYF/HYHQuQACAFqClavskGc3AGhzyd7Ti4DDrvQ8N2dgnhyiy3
          k8+xoqVq5dkraoYhGyFzekpL/XE9v0sOr8cpHNHieKyOmJDbQohfWiris5GQYC9q0DmIN
          eHrdiSAgVZhjKw97Z8HZibOH2gFPD/TSk7Lw2SG0JYFQpWdHDYlTiBbBKszfiVZA755Ha
          aBBGRudRDkYDLaIojsPLp5C65Dx41inUJMg/gMGm0SzJuAcGZgaaBdrjUyCGB1zFP/J6+
          ghl3K/yAiU7V1r+PxY9hmL/tNZ+c32Q623aS4muqjZ1iNQGeS+8lnCGTf2x5uaIRG7veH
          q1aBs85YhFSQ4ogvwqI0DABXjXwM2eDLj0s6aBp717sIwUk7roTtbVgkRaWs5WILrwE4G
          xELJhFCWVJ4enONX8Kb9kYxue1Kd6Ku9JaE+UrUDgyxKLOPDgg7S3dnchbUeg38UurKa+
          c5srPrJs5JL00hb3GVJ7ORIX4dFdYvJRAZNqExyx15kq6iPYv8QHQg5ai/XAGQ=

- job:
    name: armada-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/armada to airshipit/armada
    vars:
      git_mirror_repository: airshipit/armada
    secrets:
      - name: git_mirror_credentials
        secret: armada-airshipit-github-secret
        pass-to-parent: true

- secret:
    name: armada-airshipit-github-secret
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - QhMLTtGvYN+GvEF28brcFNk3/2mXVea9ZoPU4SqUvqy+T/0kdpGZ8RZkZ9mr6Odsl/WJl
          K3n6ct6VYv0l6kCjSLYZd2BcNXTebFEYAAPAhpaUavltMiW1pv/U+1VV1e8Ry6YQWiGII
          NjlVKN5ZGlYpuE706QcS18JV/HvzkaMMNKnp2/Yi3pGc5jWJSN4zNgZ4OiLxuuhFvyCZm
          wFMsfv+XqS7nsTO7hE7goswLcJ6CY3pYXMoLmS4jI8Xkoc/wc8AKziIAqv2yXOHrmPdWY
          NHbuGUccTA85RuDq94gkW2cz5BvR6m/cLpdbQmV5W3G2+ZVFPJtKiikImLBW29x3M22fP
          iLHN4BALD2qgoMab1+Igt+gx2ESoYaeBX0hzt2VY1D3R+r5O7fTktwdPpxcUBEVxLa0du
          NoolrCYglWCaN1F9DOCYpl/fFf4MeMUtKPiiI4p6j2vNqUMLlOq+GquB8hj4G3a30pTrr
          fbXF3/L07HutQQ+Jvvxx03aIwZAfmn0QzOTo1KrPQVCyX+HWK5CjhpPOWPqQ8lEIBaXbk
          zplLDncJrG11W3qPmRHsDfYgu82zCVZ5bn62ur+N+wstdhEeCEaP8jPWZ9dvwWwCsBX04
          RAQ0BFEQUwVr+QCz1Xi2H9SOjr7T5pVkcq1IDxVIP+6HYFWOcWgRMNtU/E4Xb0=
        - RD+YHDgMbXP4fgFbRub0JJDx6HT1IoOMjZonAqA8eB8QNc6nXoKIPp7+uSTjhXO03VoKh
          JpPYbzAKIYVPsePvI0Zi6LG08/tdD5auLLChjHrTKvNH9i7QqrBY+11THoSbdE2GQU/vq
          /8kZ053rfauTEEbHavyOstgaVe4VzYrf5GCIPWd0RLAE7+lcLdfa/hAA1zgkPz0s35stA
          sUUxRSpM2xEV6QWmNu/e0Id1X7cyAm8+ReK7aQGrRI+OH7zmbk19/kHl6CQwu0CATlkYr
          cir2oUsZLqztzZkoye+lgvuIl0MhJfVuW9T2a08I8sTUFn+7iAhsQF141E1Kim9HdhLX6
          tGEhNlSXlis6yjDOo3VClfISyYlFLipvLHcfwaIoyctR2qMBM8QZ/vobefeGCNnfnvGvc
          EO9WFlGAE+Wi0XJ+aHfnjyx3Uj0DyeYpjeaT2Z3Zh+FjHvAxf4HR61aAHsLneTNdH3jnk
          xQfQdSsxRhMNh8G672CChmHIVr65mUnCICdzRLv0n9zg+zX34GA+LuQvpchEREb5iUsGo
          USbfFPjxFredplwzbMLJhHREJmazgBscH/P1Yxm3MWvI+ui2L/FPUtDkbPA9N49boyezl
          klY9EjdiPyz0Rojv5LKPS9dD1xsbS0tTfzhJeNmAWkSpXAWYB3aD5mtmF73uWg=
        - YuZrKg3gP0lx4RX2IN0b39fCHebg4mONsZgJpOzdOwBZJmBUmjh/Vg0G5Elqn+WB/OlJ4
          O+dXavtOQtiNDSz9ysHgwTqXs7uyokt3IFio3oRTqXJC0SRss/KdknGRebFCgOm6FPKLj
          +HIRGYOzUwD4dMkEKJ5Fgeq28rqDITyiG88w7YxY4ZTmhKISHJWg/jRGq2P0jOy/W/1gB
          febTyWdEbWrMNaDADM7oHgRN4r1RNerh/CXppgcxKSIlgfxyYx3kvJXc7Z+QGVgxuHVds
          Ykgv18IYTPniXS2mXvHGbfdbg1GJwoQbzMHjhyLyTUYTPPe3afK7pSvTZTP7j1qj0Ta6J
          kLRKQx7mWIDtmQcqhO1ZQr4HnZsoNnifjO8uVvHz+HM8fqFlCfa62zndpBE/XNkoymC9I
          mqTv74XzQvCujWEprZZzcZG3YbwC3Utcoy3RjsjBbwTWp7Fg7rXbXtLfTGERt1FPvHa8c
          Sv7DLwic1IvE8CZz3E4lYhPuCTpt+sOlxW24+MiyguRXn7SJrKnOCKHsyOUOs5cwhR35X
          0hVmp3Arlu37tQNDZA1juLtw4D3bWPDPdkQcuncnQEs4n2kzEJR0Vk8XKomhJgKzXhP+B
          zybYvKpX5F56i3bfSs8as8CWLvih4kcwwj9fZvZlBtlWkL2jHwkFVBj/kQUczc=
        - J8Rf3NwfzPpSUU+F4Q+DZL7D7HC8ILNmq0lnf5lPBUVuD0Aavf4GtZPTXtozj6CXFRQob
          xJg5eoYN39lTSGyuFrRa/WOGaP8kQiCYCXw2ZKAOt9+LuMn1/rLKMyzYQClFiZTQ7/dzP
          7kqcIqPjWgbqFviwKJ+wXTE3Ntp8qaECjaLFhcOBNJK1mCt1ciEJQo7a/R9nxvSS2PT1h
          LRnXHI5s5cY4Wzg1pEBt4l+GJ8qWI/3dI35pwM/vB5/Z/y+pJhwcR8gBD+ARjdELaM5M5
          rJAouss0w+OHOYI+IDpWxbHeTP633+TFLrIqK1fAm1z6NCl2e7uGEmWbGVnvROajyCJnd
          gLPSqm1Mt7rlGvIN60VipoXgcVRpfiubhr6DXNs1XGk18qVRgyWyQS6uHjefJOhhka5HK
          kYvWhoWVlA7O3+llRTzdQsSInppREKge78pHEk4lpGWBfwFX6snHB3y90Du4BcNIt3UKY
          EjON6sxnRPCkcekmpUGqD/IXFYV/qxdvfnoDdVW5M2SZWzsHdMoJdBhL53FFaYDyPxTaR
          4+kMmn8VTejOT2zQfny3zBoxMt30hYsAjHfDS62lxYJL/404uShhAi+1bpnyy+uxU39nQ
          v3QSn8NtjBdh/WKptpsma1yZEHKAJJjfU9pmSrFHBfvokOmvTygjIC2uxP0ppo=
