# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - openstack-cover-jobs
      - docs-on-readthedocs
      - openstack-python35-jobs
      - openstack-python36-jobs
    vars:
      rtd_webhook_id: '47578'
      rtd_project_name: 'airship-armada'
    check:
      jobs:
        - openstack-tox-pep8
        - armada-chart-build-gate
        - armada-chart-build-latest-htk
        - armada-docker-build-gate-ubuntu_bionic
        - armada-docker-build-gate-ubuntu_xenial
        - armada-docker-build-gate-opensuse
        - armada-airskiff-deploy
    gate:
      jobs:
        - openstack-tox-pep8
        - armada-chart-build-gate
        - armada-docker-build-gate-ubuntu_bionic
        - armada-docker-build-gate-ubuntu_xenial
        - armada-docker-build-gate-opensuse
    post:
      jobs:
        - armada-docker-publish-ubuntu_bionic
        - armada-docker-publish-ubuntu_xenial
        - armada-docker-publish-opensuse
        - armada-upload-git-mirror

- nodeset:
    name: armada-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: armada-chart-build-gate
    description: |
      Builds Armada and Tiller charts using pinned Helm toolkit.
    timeout: 900
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: armada-single-node

- job:
    name: armada-chart-build-latest-htk
    description: |
      Builds Armada and Tiller charts using latest Helm toolkit.
    timeout: 900
    voting: false
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: armada-single-node
    vars:
      HTK_COMMIT: master

- job:
    name: armada-docker-build-gate-ubuntu_bionic
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    vars:
      publish: false
      distro: ubuntu_bionic
      tags:
        dynamic:
          patch_set: true

- job:
    name: armada-docker-build-gate-ubuntu_xenial
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    vars:
      publish: false
      distro: ubuntu_xenial
      tags:
        dynamic:
          patch_set: true

- job:
    name: armada-docker-build-gate-opensuse
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    vars:
      publish: false
      distro: opensuse_15
      tags:
        dynamic:
          patch_set: true

- job:
    name: armada-airskiff-deploy
    nodeset: armada-single-node
    description: |
      Deploy Memcached using Airskiff and submitted Armada changes.
    timeout: 9600
    voting: false
    pre-run:
      - tools/gate/playbooks/airskiff-reduce-site.yaml
      - tools/gate/playbooks/git-config.yaml
    run: tools/gate/playbooks/airskiff-deploy.yaml
    post-run: tools/gate/playbooks/debug-report.yaml
    required-projects:
      - airship/deckhand
      - airship/pegleg
      - airship/shipyard
      - airship/treasuremap
      - openstack/openstack-helm-infra
    vars:
      OSH_INFRA_PATH: "../../openstack/openstack-helm-infra"
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^examples/.*$
      - ^releasenotes/.*$
      - ^swagger/.*$

- job:
    name: armada-docker-publish-ubuntu_bionic
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    secrets:
      - airship_armada_quay_creds
    vars:
      publish: true
      distro: ubuntu_bionic
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- job:
    name: armada-docker-publish-ubuntu_xenial
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    secrets:
      - airship_armada_quay_creds
    vars:
      publish: true
      distro: ubuntu_xenial
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- job:
    name: armada-docker-publish-opensuse
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-single-node
    secrets:
      - airship_armada_quay_creds
    vars:
      publish: true
      distro: opensuse_15
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- secret:
    name: airship_armada_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - mQ5xMKaU6+ug5Zp+LK5hfwbFamnW9hK2QVQOA7ylcoTMh8yz66YcgDjGJjbT2c66NF8eg
          f279ODNmGe5pYepdR8/fU/aQ2pTVVvrF1bt0fcon8xxEZGuWnCftYZjO6Ogq+HWWwwnW0
          HLcvnFK3GhGBJkYCG9742PxuLpDOYDSiK3jRCN1tgdY+vcHpm7bwqyhzywj7ar4lsk8Gk
          d9Z57xkcURuw/GEBf8tHzd2PTAj3Oao6hKMTdCVhYZejjNNR34GPhGIvipb7m/dNIzT2c
          j4a/Kq3HcqVog1OiCkSn4jRlIcD1Jgl/cyJyEz6dZCP2W16X/qwzDD8YUSsTPt4Jc6s/U
          hD/aye5f1Jwoiyy23BM7BJ8s8eoioYsubV3TUGNQv64UxRnd4nPyWW2QssfAlA2fsww2v
          D9nLjmYuj4t8IzfQVd4ZLwBUKrb1q1au8bR3jYd8x2RaYjAVr4aPXQLzeXR7k0kZ9QgYO
          PetkCkf2vly8UYtonaM0odf7X1KfKgCOU+urXWMnDVU3SEaMH5f51NnW8Xb5NmCk/S9vz
          MVl6IR/ZCa9q7sIH40B2Tt61AsU1RjIyAahU6fkg/pW19uBv7zI6BDSZUiEh662MnK4z1
          O5n0771VjSa2aqpP1+iTkDWqobcSvgvHWQCM4Cv4fBO//E7s/LV0FIayQYbm2k=
      password: !encrypted/pkcs1-oaep
        - nATf8olUzHg6pBmRJ2KF9NI48axKYtuFn7j8R8iKRfV3R7NW3eq89gsk5m9DVq4+GUEGw
          ZxLRjy2/F31Xnw2snGf7Pj+33O1NRSZ7D/UqKSu07tS0qkRn4rWK6U4tO1crHb7NPqd3I
          rziVgOCTBpaKNLBlEEYqYF/HYHQuQACAFqClavskGc3AGhzyd7Ti4DDrvQ8N2dgnhyiy3
          k8+xoqVq5dkraoYhGyFzekpL/XE9v0sOr8cpHNHieKyOmJDbQohfWiris5GQYC9q0DmIN
          eHrdiSAgVZhjKw97Z8HZibOH2gFPD/TSk7Lw2SG0JYFQpWdHDYlTiBbBKszfiVZA755Ha
          aBBGRudRDkYDLaIojsPLp5C65Dx41inUJMg/gMGm0SzJuAcGZgaaBdrjUyCGB1zFP/J6+
          ghl3K/yAiU7V1r+PxY9hmL/tNZ+c32Q623aS4muqjZ1iNQGeS+8lnCGTf2x5uaIRG7veH
          q1aBs85YhFSQ4ogvwqI0DABXjXwM2eDLj0s6aBp717sIwUk7roTtbVgkRaWs5WILrwE4G
          xELJhFCWVJ4enONX8Kb9kYxue1Kd6Ku9JaE+UrUDgyxKLOPDgg7S3dnchbUeg38UurKa+
          c5srPrJs5JL00hb3GVJ7ORIX4dFdYvJRAZNqExyx15kq6iPYv8QHQg5ai/XAGQ=

- job:
    name: armada-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/armada to airshipit/armada
    vars:
      git_mirror_repository: airshipit/armada
    secrets:
      - name: git_mirror_credentials
        secret: armada-airshipit-github-secret
        pass-to-parent: true

- secret:
    name: armada-airshipit-github-secret
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - O+CbBn3k5fyLR9uCiEB0ILNV33Ped2gSc+emTX6HbN/qmNRWYu7SsP5rA0+oG7laf+uVe
          qwpy/MDwoFHs2HnUG8vwEOxH89ojDeS778o849S3/2d4Yqwiyjgn2e+dby3V6f+Q9e45Q
          UpImryS5e8KtEljC3wh6grgS4ziFJ/N0hQ0kpTfNwEmboYcsQ7msS1Il60sSnBmNhypdz
          XgCOAt9LmGcPZWl/hEyMD5KpqWQMruYWHzg1FjLdHCO79oSS5mdtdQvGbu0gFbBA+v9Fa
          x8MkAu0i5+HCEiJTGKv738LqJSpnRbGLrmoG3sNWBitvQu2sSGMC/qIRiMB8YfI1V7w+7
          CNRnDqfutucetZFNXbtKna3E+lHmK9j6e7vyNSl+jttC0rRVa0KlQo/1+lPmaEe8/Aaay
          2ohiFMVn/Xf1AhZpcQt0ixN95cxYobyWQIYdgfSedS7mjH7/5O0TNdpEVur8HFS+LcgZo
          g6f/6eRiFN9J09pQGW8FdH4cr5uRqACId7Cuw+KA03+a5v8zSBRLr0t46nKlsUG4OOKLt
          Te84Rf/3OuR1IL2nIvzTTY3290Lxs4EkwPMrs2eyh/mTgPV4budll0RJO8oFI2g7Bkk66
          38oJKgNFaQnO1mONNIF0Zxx95g0hvDPB0Q1R6cBZuughvonswnaaN8aFCu5Mqc=
        - Ij1FXTlxa4Rdl5FUh7Zhswc503UYu/76QTZXQpsrmUXzVzFKUpg52pOCFO1XulTgGGB/n
          7/94UlgzxUsHAUENLFok1iEnmwexzuEmta7tqMoWTqOk9oW1fPCjYMWeN/F5Cq4uD0FH8
          fib2J7UxSYqFBU3dVbNR+krYLB13PdEs2nJrE8UxdscBR+Z7YhfXz4LfCEwE7rmpLhbqD
          Cl1ARwro0f1S6uj9hB1Pwg3iaZrYJDLE+Qr/oAZETONouXPus6+cZ+Gvn+sWaQtt7CtFu
          CxF0vlJSfZV0VLu04nDz2LAlcJWKbtBeMqGA0kfVAa5dC7kHfbCd3DU2423N/2ezj5gY9
          C6t2n1eEwUWKoX0MEpfxc8pkUk7EhWABClcHV732mrfcxF/cbAfdyoiGuz1IH3ILZ+vQ7
          yGB0n0/JKLtXTTsbfqM45ml5HxHaxCYYVK+5F5CFnVXUEujZw5C3JEZWyYCSiqmLvbMM4
          GkCILPmk7K1qoTk6P5AHjJU+jgBNboy+vdlOMW1nkAh9VmzwjxYmY9MajadYSS9NeF0UK
          0A1n1BAa5PzFnNTllzWalQ07kzqGg4y/q5skE4bTMzZnImEJhwnIl9hoX/k9hhuq3x0ss
          y6YfVBmJLniytCWz1V8/Uwpo835iCBvsrsmFwfAjokrPdDijc4+dRVXv2vjt+4=
        - Du8DIpxYdtr5sQdE1cjiSq7yCLMTPEUsY3TqbkBkZz9xr4tUG6bae8VAnbjVVN9t7gilQ
          vOyczZV1efFFGqtMZ27jYY+zf/uEZGEOH7voIBswP80IgDYqm2DRVWpp7bMBqLXm6edT9
          Km24U5YWAmQWsrTVM9acPlqnY8RMCx4MgyVsH0v5fV0kOPHFJYgnQzwMQq5z+Bjzz5YUJ
          grSk5hqkfWDmrzR5QxkFeKtTTqiKchbjUaM1VrJmlMHBxW2PxVU7G3iQtYFdXjwmR7kKq
          BU1UJLSIFMCuNsmPiMVvUhI5eXula1LAqdFhrhnhEzSNSyb+JLxQsB4rfp4sY2LvGMnXw
          YCAAM7ihi2XSBFckmPNf0wqixdBPT/ak4iX57jAZIQ8YC6Vnehr4NzPpcIUvXp83fzSf/
          qFIOo8+yHnOuNxSLtxxRO8MJzn2ryK1X4CyQe/yXNsuz32hK2+zojbZnHoLZgDvN6ZZhb
          /xvm/jP3Np44C4pxYh9ue0lPSjmWJqQIL5/FZr4ErgDqQziAbkdOZQl+IxjRM8mBNKeUg
          ecRk/zGGa94trPO/P7GIHmzGV0qaZLYwHW/OZNlfcRY1DPop+wLYTLirXoAfxK1fynxbu
          4tPcgt/avxu9zHBdcHtVpMCpr2EgMTzA+U45VKVZyLBACdOjMcJ7pmJLmYzkp8=
        - mzG8+8DTfHn/BA9Z6AOhU2hdig7IY2I055lUT37qT4KWX+oWjfHCh61454gSUW75CJOHj
          02CDyBpT6uxVPz34VlTMRuJFHvUrQxBFCzBChaTW3IDKMt7v2Zo4IBWcs6dyjKmFnhUnC
          inS2LFOxKE3YGlJtYjPG58K7vT46Xa8lispulhOU5g7gHidYYDE5RVQJ3HILamwaFjp8Q
          G5tNlbBXGq0+OcxZN+R2gvNmNE16aiTzXVkpdCz3kc/0+Miqb6kA5phytHjiEWlPYKXgr
          PypIM8nYJj46KkEbE4eKU+EfK0srjhPEX1WCKcDlpAttmhRhgZ1Z8F0UeaRc+jhN/Peh4
          mLQhJzq8mlvwmAX8sxbMJFwBPUVh9PzcDW1qz+fLJ6X+8b0CZ77lqEOnUarTCokvOC6eR
          N4asWQmWeCQJg0hP4jEyfNilvyCAPHUIY0+G8kaMN260bB4uJdets391vhDegqaThLygI
          8HScjwczBFoyf0nunqsf5pj24mwcsNqFYe/R1tQi7SBO23EFde/lueWwkU51oRjg2pC3l
          kDSxbmHBFs+X8LoaM69TxL4K1xLwyYK4zxfg5PP4hr6WRCUgm3x9xyRsuoTa7fPcHQgId
          mFPhk3x2s5Ls/8s7HElq/AoMc/Lr/qQqVlSkTCEyiB68fSizg2pI8ox+uqcZ9c=
