apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: armada-controller
  labels:
    rbac.armada.airshipit.org/aggregate-to-armada: "true"
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
      - extensions
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
  - apiGroups:
      - armada.process
    resources:
      - locks
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - armada.airshipit.org
    resources:
      - armadacharts
    verbs:
      - get
      - list
---
