..
  Copyright 2017 AT&T Intellectual Property.
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License.

Tiller Exceptions
-----------------

.. currentmodule:: armada.exceptions.tiller_exceptions

.. autoexception:: ChannelException
   :members:
   :show-inheritance:
   :undoc-members:

.. autoexception:: GetReleaseStatusException
   :members:
   :show-inheritance:
   :undoc-members:

.. autoexception:: PostUpdateJobCreateException
   :members:
   :show-inheritance:
   :undoc-members:

.. autoexception:: PreUpdateJobDeleteException
   :members:
   :show-inheritance:
   :undoc-members:

.. autoexception:: ReleaseException
   :members:
   :show-inheritance:
   :undoc-members:

.. autoexception:: TillerListReleasesPagingException
   :members:
   :show-inheritance:
   :undoc-members:
